/**
 * The home screen icons. `default` is the app's own icon; the others are the
 * alternate icons generated by `scripts/generate-alt-icons.mjs` and registered
 * with `expo-alternate-app-icons` in `app.json` (the plugin entry names must
 * equal `nativeName`; a test pins that).
 */

export const APP_ICON_IDS = ["default", "midnight", "ember", "mono"] as const;

export type AppIconId = (typeof APP_ICON_IDS)[number];

export interface AppIconOption {
  id: AppIconId;
  label: string;
  description: string;
  /** The alternate icon name iOS knows; null for the default icon. */
  nativeName: string | null;
}

export const APP_ICONS: readonly AppIconOption[] = [
  {
    id: "default",
    label: "Default",
    description: "The orange book",
    nativeName: null,
  },
  {
    id: "midnight",
    label: "Midnight",
    description: "Orange on warm charcoal",
    nativeName: "Midnight",
  },
  {
    id: "ember",
    label: "Ember",
    description: "Cream book on logo orange",
    nativeName: "Ember",
  },
  {
    id: "mono",
    label: "Mono",
    description: "One ink on cream",
    nativeName: "Mono",
  },
];

export function appIconOption(id: AppIconId): AppIconOption {
  return APP_ICONS.find((icon) => icon.id === id) ?? APP_ICONS[0];
}

/** The icon iOS reports as active; anything unknown counts as the default. */
export function appIconFromNativeName(
  name: string | null | undefined
): AppIconId {
  return APP_ICONS.find((icon) => icon.nativeName === name)?.id ?? "default";
}

/** Choosing anything but the default icon is the Pro supporter perk. */
export function isGatedAppIcon(id: AppIconId): boolean {
  return id !== "default";
}
